### ISSUE TITLE
3D spatial distribution

### ISSUE THREAD

**Issue by saharsh1** [ArtificialStellarPopulations/ArtPop#13]
In light of the upcoming Gaia DR3, it might be nice to enable 3D spatial distribution of stellar populations. 

If these distributions could be assigned differently for each sub-population (say young\old, low\high metallicity, etc.), and easily reflect the structure of the Solar neighborhood, it would be extremely nice :)

**Comment by johnnygreco** [comment]
Hey @saharsh1!

Apologies for the long delay but I believe you and @shanyDanieli talked about this issue in person a while back? This would definitely be a neat feature! We'd need to make it possible for the distance to be an array – one distance per star. Then the easiest way to get the sub-populations would be to make [custom source objects](https://artpop.readthedocs.io/en/latest/tutorials/source.html) for each one and then add them together.

**Comment by johnnygreco** [comment]
Closing for now as it seems interest isn't too high at the moment.
