### ISSUE TITLE
How to generate a source with only main sequence stars?

### ISSUE THREAD

**Issue by PaulLiu666** [ArtificialStellarPopulations/ArtPop#15]
Firstly, I built stellar populations  and drew HR-diagram of the stellar evolution stages that interest me.
![image](https://github.com/ArtificialStellarPopulations/ArtPop/assets/94830897/64e8afe5-ae0b-4245-9549-be0c8a8e5f2d)
Then I wanted to generate a source with only the main sequence star, and I used the following code, but there were errors. How can I input the values of labels to obtain the desired results?
<img width="329" alt="截屏2023-06-06 11 12 09" src="https://github.com/ArtificialStellarPopulations/ArtPop/assets/94830897/d1e0b994-2834-419b-825f-9e8f4c038a9c">
Thank you very much for your help!

**Comment by johnnygreco** [comment]
Hey @PaulLiu666 – I think the simplest approach would be to build the source object from the ground up:  

- generate a stellar population and use the MS-star boolean mask to get the stellar mags (like you did to make the figure)
- generate xy positions for each star using [sersic_xy](https://artpop.readthedocs.io/en/latest/api/artpop.space.sersic_xy.html#artpop.space.sersic_xy)
- Use the xy positions and mags to initialize a [Source](https://artpop.readthedocs.io/en/latest/api/artpop.source.Source.html#artpop.source.Source) object.

If your end goal is to simply create an RGB image of the source, the `observe` method of [Imager](https://artpop.readthedocs.io/en/latest/api/artpop.image.ArtImager.html#artpop.image.ArtImager) objects have an optional `mask` argument for selecting the stars you want to inject.
 
This is how we made the figure below in the [ArtPop paper](https://ui.adsabs.harvard.edu/abs/2022ApJ...941...26G/abstract):

![phase-ssp-grid](https://github.com/ArtificialStellarPopulations/ArtPop/assets/10998105/69e043e3-798f-409b-90fc-cf6b15bbea2e)


The script for making this figure is [here](StellarPopulations/artpop-paper-figures/blob/main/scripts/figure_5_greco_and_danieli.py).

**Comment by PaulLiu666** [comment]
@johnnygreco Thank you very much!
