### ISSUE TITLE
JWST filters?

### ISSUE THREAD

**Issue by MilesCranmer** [ArtificialStellarPopulations/ArtPop#19]
Hey all,

Would it be possible to include the JWST filters by any chance?

Cheers!
Miles

By the way, what is the proper way to specify a custom set of filters? (e.g., if I simply have a numpy arrays specifying a bandpass)

**Comment by shanyDanieli** [comment]
Hi Miles!

The JWST filter set is already included. To get the full list of JWST filters, try:
```python
import artpop
artpop.get_filter_names('JWST')
``` 

To add a new custom set of filters, please see Johnny's reply to issue #17.

Please let me know if you have any questions!

**Comment by MilesCranmer** [comment]
Thanks! 

For what it's worth I think my confusion arose because most filters are prefixed by the observatory (like `2MASS_H` or `DECam_g` or `GALEX_FUV`) but JWST is not (like `F070W` rather than `JWST_F070W`).
